### ISSUE TITLE
No invoice mail is sent to the customer and BCC after updating to M2.2.4

### ISSUE THREAD

**Issue by Esteraa** [MultiSafepay/Magento2Msp#69]
After updating to M2.2.4, the invoice mail is not sent to the customer and to the filled in BCC email address. This is only the case when the payment is successfully paid trough MSP payments and the invoice is created automatically. When creating an invoice manually, the invoice is sent to the customer and to the BCC email address.

We are using MSP 1.5.0 and M2.2.4.

**Comment by Jasper-MultiSafepay** [comment]
Can I assume the setting "E-mail invoice to customer" is set to "Yes" within the MultiSafepay Settings?
If this is already the case and the invoice mail is not being sent, could you sent an email to techsupport@multisafepay.com so we can investigate this?

**Comment by Esteraa** [comment]
Yes the setting is set on "yes", I also tried this with the setting "no".  With both options, there was no invoice sent. Ok, I will send an email.

**Comment by Jasper-MultiSafepay** [comment]
Solved with https://github.com/magento/magento2/issues/13466

**Comment by Darkbelg** [comment]
We are still experiencing this issue. Is there any other solution for this ? Because Magento has acknowledged the issue but has not yet fixed it.
